name: My First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Message
        run: echo "Hello Sandesh! GitHub Actions is working!"

      - name: Show Files
        run: ls -la
      - name: Print Date
        run: date
